# Generated by Django 5.2.17 on 2026-10-05 06:14

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WalletPass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serial_number",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "organization_name",
                    models.CharField(
                        default="Johan Rivera",
                        max_length=60,
                        verbose_name="organización",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        default="Tarjeta personal",
                        max_length=120,
                        verbose_name="descripción",
                    ),
                ),
                (
                    "logo_text",
                    models.CharField(
                        default="JOHAN RIVERA",
                        max_length=30,
                        verbose_name="texto del logo",
                    ),
                ),
                (
                    "member_name",
                    models.CharField(max_length=40, verbose_name="miembro"),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True, default="Black", max_length=20, verbose_name="nivel"
                    ),
                ),
                (
                    "member_since",
                    models.CharField(
                        blank=True,
                        default="2026",
                        max_length=20,
                        verbose_name="miembro desde",
                    ),
                ),
                ("member_id", models.CharField(max_length=30, verbose_name="ID")),
                (
                    "barcode_message",
                    models.CharField(
                        blank=True,
                        help_text="Vacío = usa el ID.",
                        max_length=200,
                        verbose_name="contenido del QR",
                    ),
                ),
                (
                    "back_info",
                    models.TextField(blank=True, verbose_name="info del reverso"),
                ),
                (
                    "background_color",
                    models.CharField(
                        default="#121218",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9A-Fa-f]{6}$", "Usa un color hex como #121218."
                            )
                        ],
                        verbose_name="fondo",
                    ),
                ),
                (
                    "foreground_color",
                    models.CharField(
                        default="#FFFFFF",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9A-Fa-f]{6}$", "Usa un color hex como #121218."
                            )
                        ],
                        verbose_name="texto",
                    ),
                ),
                (
                    "label_color",
                    models.CharField(
                        default="#D4AF37",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9A-Fa-f]{6}$", "Usa un color hex como #121218."
                            )
                        ],
                        verbose_name="etiquetas",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, upload_to="passes/logos/", verbose_name="logo"
                    ),
                ),
                (
                    "strip",
                    models.ImageField(
                        blank=True, upload_to="passes/strips/", verbose_name="franja"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "pase",
                "ordering": ["-created_at"],
            },
        ),
    ]
