# Generated by Django 5.2.17 on 2026-10-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="walletpass",
            name="logo_text",
            field=models.CharField(
                default="GRUPO X", max_length=30, verbose_name="texto del logo"
            ),
        ),
        migrations.AlterField(
            model_name="walletpass",
            name="organization_name",
            field=models.CharField(
                default="Grupo X", max_length=60, verbose_name="organización"
            ),
        ),
    ]
